/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package com.mycompany.finalproject;


import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;

/**
 *
 * @author YTAC
 */
public class BuyDialog extends java.awt.Dialog {

    /**
     * Creates new form BuyDialog
     */
    Main parent;
    ArrayList<Top> cartT;
    ArrayList<Accessory> cartA;
    
    Top itemT = null;
    Accessory itemA = null;
    
    public BuyDialog(java.awt.Frame parent, boolean modal, ArrayList<Top> cart, Top item) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.parent = (Main) parent;
        cartT = cart;
        itemT = item;
        this.icon.setIcon(item.getProductIcon());
        this.name.setText(item.getProductName());
        this.total.setText(String.format("Total: %.2f", item.getTotal()));
    }
    
    public BuyDialog(java.awt.Frame parent, boolean modal, ArrayList<Accessory> cart, Accessory item) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.parent = (Main) parent;
        cartA = cart;
        itemA = item;
        this.icon.setIcon(item.getProductIcon());
        this.name.setText(item.getProductName());
        this.total.setText(String.format("Total: %.2f", item.getTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        buy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        icon.setForeground(new java.awt.Color(0, 0, 0));
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/A.png"))); // NOI18N

        total.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("Total:");

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText("Name");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COD", "Online Payment" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Payment Method:");

        cash.setEditable(false);

        buy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buy.setText("Buy Now");
        buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Payment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(icon)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buy)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(total))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(total)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(buy)))
                .addGap(18, 18, 18)
                .addComponent(name)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public void deleteItem(Top item) {
        int index = -1;
        
        for (int i = 0; i < cartT.size(); i++) {
                
            Top itemOnCart = cartT.get(i);
            if (itemT.getProductName().equals(itemOnCart.getProductName())
                && itemT.getSize().equals(itemOnCart.getSize())) {
                index = i;
                break;
            }
        }
        
        if (index == -1) return;
        
        cartT.remove(index);
    }
    
    public void deleteItem(Accessory item) {
        int index = -1;
        for (int i = 0; i < cartA.size(); i++) {
            Accessory itemOnCart = cartA.get(i);
            if (itemA.getProductName().equals(itemOnCart.getProductName())) {
                index = i;
                break;
            }
        }  
        if (index == -1) return;
        
        cartA.remove(index);
    }
    
    private void buyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyActionPerformed
        DefaultTableModel tbl = parent.getTableModel();
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");  
        LocalDateTime now = LocalDateTime.now();
        
        String paymentmethod = "COD";
        double pay = 0;
        
        if (jComboBox1.getSelectedIndex() == 1) {
            try {
                paymentmethod = "Online";
                pay = Double.parseDouble(cash.getText());
            } catch (Exception e) {
                return;
            }
        }
        
        if (itemT != null) {
            
            if (jComboBox1.getSelectedIndex() == 1 && pay < itemT.getTotal())
                return;
            
            Object[] row = {
                itemT.getProductName(),
                itemT.getClass().toString(),
                itemT.getSize(),
                itemT.getProductPrice(),
                itemT.getAmount(),
                itemT.getTotal(),
                paymentmethod,
                0.00,
                pay - itemT.getTotal(),
                dtf.format(now)
            };
            
            tbl.addRow(row);
        } else {
            
            if (jComboBox1.getSelectedIndex() == 1 && pay < itemA.getTotal())
                return;
            
            Object[] row = {
                itemA.getProductName(),
                itemA.getClass().toString(),
                "",
                itemA.getProductPrice(),
                itemA.getAmount(),
                itemA.getTotal(),
                paymentmethod,
                pay,
                pay - itemA.getTotal(),
                dtf.format(now)
            };
            
            tbl.addRow(row);
        }
        
        parent.renderCartPanel();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_buyActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        if ("Online Payment".equals(jComboBox1.getSelectedItem())) 
            cash.setEditable(true);
        else {
            cash.setEditable(false);
            cash.setText("");
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buy;
    private javax.swing.JTextField cash;
    private javax.swing.JLabel icon;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
